### ISSUE TITLE
Inconsistent types for StreamOptions vs. UserIdCollection

### ISSUE THREAD

**Issue by finsterdexter** [Twitterizer/Twitterizer#3]
Apparently, UserIdCollection is storing user IDs as decimals? Any reason not to use `int` or `long`?

Also, the StreamOptions Follow property is a `List<string>`.

See the problem here? So, in my implementation, I have to convert the `UserIdCollection` from a collection of decimal to a `List<string>`. Seems like these should be normalized to a single type. Either return a `List<string>` from `TwitterFriendship.FriendIds`, or change `StreamOptions` Follow to `UserIdCollection`. (Although, what should probably happen is have them both normalized to `List<int>`, or `List<long>` if we think twitter will get over 2 billion users.)

**Comment by DigitallyBorn** [comment]
Twitter is one of the fastest growing services on the internet. It may seems silly to use such a large datatype for an identity field, but I opted to allow for a very long life before I am forced to introduce a breaking change to the library. Use of the decimal datatype was also to keep identities consistant, since the status id requires a very large datatype. (It rolled past Int32 in June 2009.)

You're right that the follow property should be a numeric datatype.

**Comment by finsterdexter** [comment]
That makes sense.
