### ISSUE TITLE
Sqlite datatype for ID's

### ISSUE THREAD

**Issue by Redth** [Twitterizer/Twitterizer#44]
I see you're using decimal as the data type for ID's on objects.  That's all good and fine, but wondering what the actual impact is.  How many decimal places should we be expecting?  I'm trying to create the schema for a SQLite database and want to know what DECIMAL(X,Y) to use to store it.

Thanks!

**Comment by DigitallyBorn** [comment]
Twitter IDs will never have anything right of the decimal point. That is to say they will always be whole numbers (at least until they say otherwise). Decimal was used as the datatype because it is the largest non-floating point number available and, given the pace in which twitter grows, I felt allowing a very large space for growth would be the better way to go.
